apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tasks-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api 
    spec: 
      containers:
        - name: tasks-api 
          image: slobodang/kub-demo-tasks-api
          env:
            - name: AUTH_ADDRESS
              # value: 10.102.45.247 
              value: "auth-api-service.default"
            - name: TASKS_FOLDER
              value: tasks



